name       : pyprind
version    : 2.11.0
release    : 2
source     :
    - https://github.com/rasbt/pyprind/archive/2.11.0.tar.gz : 3e7646c6b043b50766d63c1c14e081bcda4ac6a1394902e7fec35ad386c91b1a
license    : BSD-3-Clause
component  : programming.python
summary    : Python Progress Bar and Percent Indicator Utility
description: |
    The PyPrind (Python Progress Indicator) module provides a progress bar and a percentage indicator object that let you track the progress of a loop structure or other iterative computation.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

