name       : pyprind
version    : 2.11.2
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/P/PyPrind/PyPrind-2.11.2.tar.gz : c46cab453b805852853dfe29fd933aa88a2a516153909c695b098e9161a9e675
license    : BSD-3-Clause
component  : programming.python
summary    : Python Progress Bar and Percent Indicator Utility
description: |
    The PyPrind (Python Progress Indicator) module provides a progress bar and a percentage indicator object that let you track the progress of a loop structure or other iterative computation.
setup      : |
    %python3_setup
install    : |
    %python3_install
